Repository UFOMG/ufomg-fe, pull requests merged in 2021-03, with the labels that each got.

#45 Feature/comments post
  package.json
  src/Components/App/App.js
  src/Components/CommentForm/CommentForm.js
  src/Components/CommentPage/CommentPage.js
  src/Components/MainPage/MainPage.js
  src/actions/index.js
  src/api.js
  src/reducers/sightings.js
  src/utilities/mapSetup.js
Labels: Front-End, enhancement

#52 Feature/research comments
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/CommentForm/CommentForm.js
  src/Components/CommentPage/CommentPage.scss
  src/Components/MainPage/MainPage.scss
  src/Components/MainPage/MainPage.test.js
  src/Components/MapDisplay/MapDisplay.js
  src/Components/MapDisplay/MapDisplay.scss
  src/Components/ReportForm/ReportForm.js
  src/Components/ReportForm/ReportForm.scss
  src/Components/ReportForm/ReportForm.test.js
  src/Components/SightingsFilter/SightingsFilter.js
  src/Components/SightingsFilter/SightingsFilter.scss
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.test.js
  src/actions/index.js
  src/api.js
Labels: Front-End, enhancement

#53 Feature/comment styling
  src/Components/CommentPage/CommentPage.js
  src/Components/CommentPage/CommentPage.scss
  src/Components/ReportForm/ReportForm.js
  src/Components/ReportForm/ReportForm.scss
  src/Components/SightingsFilter/SightingsFilter.scss
Labels: Front-End, styling

#54 Feature/cleanup
  src/Components/CommentPage/CommentPage.js
  src/Components/MainPage/MainPage.js
  src/Components/MainPage/MainPage.scss
  src/Components/ReportForm/ReportForm.js
  src/Components/SightingsFilter/SightingsFilter.js
  src/Components/SightingsFilter/SightingsFilter.scss
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.scss
  src/utilities/mapSetup.js
Labels: enhancement

#55 Testing/add cypress tests
  cypress/integration/App_spec.js
  package-lock.json
Labels: testing

#58 Bug/sighting map
  src/Components/SightingsMap/SightingsMap.js
  src/utilities/mapSetup.js
Labels: Front-End, bug

#61 add readme
  README.md
Labels: Front-End, documentation
