Repository UFOMG/ufomg-fe, pull requests merged in 2021-02, with the labels that each got.

#5 Feature/app structure
  cypress.json
  cypress/fixtures/example.json
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/App.test.js
  src/Components/App/App.css
  src/Components/App/App.js
  src/Components/MainPage/MainPage.js
  src/Components/MainPage/MainPage.scss
  src/Components/MainPage/MainPage.test.js
  src/Components/ReportForm/ReportForm.js
  src/Components/ReportForm/ReportForm.scss
  src/Components/ReportForm/ReportForm.test.js
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.scss
  src/Components/SightingsMap/SightingsMap.test.js
  src/assets/alien-head.jpg
  src/index.css
  src/index.js
  src/logo.svg
  src/reportWebVitals.js
  src/setupTests.js
Labels: enhancement

#10 Feature/redux
  package-lock.json
  package.json
  src/Components/ReportForm/ReportForm.js
  src/actions/index.js
  src/index.js
  src/reducers/index.js
  src/reducers/sightings.js
Labels: Front-End, enhancement

#15 Feature/map integration
  .gitignore
  package-lock.json
  package.json
  src/Components/App/App.js
  src/Components/MapDisplay/MapDisplay.js
  src/Components/MapDisplay/MapDisplay.scss
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.scss
  src/assets/alienmarker.png
  src/assets/mapSetup.js
  src/assets/skylights.png
  src/assets/ufobeam.png
  src/mockdata.js
Labels: Front-End, enhancement

#24 Feature/setting store
  package-lock.json
  package.json
  src/Components/MainPage/MainPage.js
  src/Components/SightingsMap/SightingsMap.js
  src/actions/index.js
  src/api.js
  src/index.js
  src/mockdata.js
  src/reducers/index.js
  src/reducers/sightings.js
Labels: Front-End, enhancement

#25 Feature/post sighting
  src/Components/MainPage/MainPage.js
  src/Components/ReportForm/ReportForm.js
  src/Components/SightingsMap/SightingsMap.js
  src/actions/index.js
  src/api.js
  src/reducers/sightings.js
Labels: Front-End, enhancement

#26 Testing/cypress integration tests
  cypress/integration/App_spec.js
  package-lock.json
Labels: testing

#28 Feature/main styling
  package-lock.json
  src/Components/MainPage/MainPage.js
  src/Components/MainPage/MainPage.scss
  src/Components/ReportForm/ReportForm.scss
  src/assets/alien-head.jpg
  src/assets/alien-outline.png
Labels: Front-End, styling

#30 Feature/geolocation
  package-lock.json
  package.json
  public/index.html
  src/Components/ReportForm/ReportForm.js
  src/Components/UploadWidget/UploadWidget.js
  src/api.js
Labels: Front-End, enhancement

#34 Feature/heatmap
  package-lock.json
  package.json
  src/Components/ReportForm/ReportForm.js
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.scss
  src/api.js
  src/assets/mapSetup.js
Labels: Front-End, enhancement

#36 Feature/animations
  src/Components/MainPage/MainPage.js
  src/Components/MainPage/MainPage.scss
  src/assets/alienmarker.png
Labels: Front-End, styling

#35 Feature/filter sightings
  src/Components/App/App.js
  src/Components/MainPage/MainPage.js
  src/Components/ReportForm/ReportForm.js
  src/Components/SightingsFilter/SightingsFilter.js
  src/Components/SightingsFilter/SightingsFilter.scss
  src/assets/alienstock.jpeg
  src/assets/lightsstock.jpeg
  src/assets/mapSetup.js
  src/assets/ufostock.jpeg
Labels: Front-End, enhancement

#37 Feature/comment page
  src/Components/App/App.js
  src/Components/CommentForm/CommentForm.js
  src/Components/CommentForm/CommentForm.scss
  src/Components/CommentPage/CommentPage.js
  src/Components/CommentPage/CommentPage.scss
  src/Components/MainPage/MainPage.js
  src/Components/SightingsMap/SightingsMap.js
Labels: Front-End, enhancement

#40 Feature/map additions
  src/Components/MapDisplay/MapDisplay.scss
  src/Components/SightingsFilter/SightingsFilter.js
  src/Components/SightingsMap/SightingsMap.js
  src/Components/SightingsMap/SightingsMap.scss
  src/assets/blue-blur.png
  src/assets/green-blur.png
  src/assets/red-blur.png
  src/utilities/mapSetup.js
Labels: Front-End, enhancement
